# Spark

**TODO**:

* Funciones de transformacion
* Funciones de action
* Joins
* SparkSQL
* Tuning

In [2]:
import pandas as pd
import numpy as np
import matplotlib as mp

In [11]:
rdd = sc.textFile('student-mat.csv')

AttributeError: 'SparkContext' object has no attribute 'read'

In [15]:
headers = rdd.first().split(',')
headers

['school',
 'sex',
 'age',
 'address',
 'famsize',
 'Pstatus',
 'Medu',
 'Fedu',
 'Mjob',
 'Fjob',
 'reason',
 'guardian',
 'traveltime',
 'studytime',
 'failures',
 'schoolsup',
 'famsup',
 'paid',
 'activities',
 'nursery',
 'higher',
 'internet',
 'romantic',
 'famrel',
 'freetime',
 'goout',
 'Dalc',
 'Walc',
 'health',
 'absences',
 'G1',
 'G2',
 'G3']

In [20]:
#First field:
rdd.map(lambda x: x.split(',')).take(5)

[['school',
  'sex',
  'age',
  'address',
  'famsize',
  'Pstatus',
  'Medu',
  'Fedu',
  'Mjob',
  'Fjob',
  'reason',
  'guardian',
  'traveltime',
  'studytime',
  'failures',
  'schoolsup',
  'famsup',
  'paid',
  'activities',
  'nursery',
  'higher',
  'internet',
  'romantic',
  'famrel',
  'freetime',
  'goout',
  'Dalc',
  'Walc',
  'health',
  'absences',
  'G1',
  'G2',
  'G3'],
 ['GP',
  'F',
  '18',
  'U',
  'GT3',
  'A',
  '4',
  '4',
  'at_home',
  'teacher',
  'course',
  'mother',
  '2',
  '2',
  '0',
  'yes',
  'no',
  'no',
  'no',
  'yes',
  'yes',
  'no',
  'no',
  '4',
  '3',
  '4',
  '1',
  '1',
  '3',
  '6',
  '5',
  '6',
  '6'],
 ['GP',
  'F',
  '17',
  'U',
  'GT3',
  'T',
  '1',
  '1',
  'at_home',
  'other',
  'course',
  'father',
  '1',
  '2',
  '0',
  'no',
  'yes',
  'no',
  'no',
  'no',
  'yes',
  'yes',
  'no',
  '5',
  '3',
  '3',
  '1',
  '1',
  '3',
  '4',
  '5',
  '5',
  '6'],
 ['GP',
  'F',
  '15',
  'U',
  'LE3',
  'T',
  '1',
  '1',
  'at_home',
  'other',
  'other',
  'mother',
  '1',
  '2',
  '3',
  'yes',
  'no',
  'yes',
  'no',
  'yes',
  'yes',
  'yes',
  'no',
  '4',
  '3',
  '2',
  '2',
  '3',
  '3',
  '10',
  '7',
  '8',
  '10'],
 ['GP',
  'F',
  '15',
  'U',
  'GT3',
  'T',
  '4',
  '2',
  'health',
  'services',
  'home',
  'mother',
  '1',
  '3',
  '0',
  'no',
  'yes',
  'yes',
  'yes',
  'yes',
  'yes',
  'yes',
  'yes',
  '3',
  '2',
  '2',
  '1',
  '1',
  '5',
  '2',
  '15',
  '14',
  '15']]